#pragma once
#define MAIN_DIALOG_TITLE _T("Nouse Settings")
#define MAIN_CONTROL_SETTINGS _T("Control Settings")
#define COUNTDOWN_DWELL_TIME _T("Countdown Dwell Time")
#define CURSOR_SIZE _T("Cursor Size")
#define CURSOR_SPEED _T("Cursor Speed")
#define JOYSTICK_DEFAULT _T("Joystick Default")
#define DIRECT _T("Direct")
#define DISCRETE _T("Discrete")
#define COUNTDOWN_CALIBRATION_TIME _T("Countdown Calibration Time")
#define ENABLE_YELLOW_STATE _T("Enable Yellow State")
#define ENABLE_SOUNDS _T("Enable Sounds")
#define MAIN_RECOGNITION_SETTINGS _T("Recognition Settings")
#define VERTICAL_RANGE_OF_MOTION _T("Vertical Range of Motion")
#define HORIZONTAL_RANGE_OF_MOTION _T("Horizontal Range of Motion")
#define RESOLUTION_IN_PIXELS _T("Resolution in Pixels")
#define RESOLUTION_IN_SECONDS _T("Resolution in Seconds")
#define ACTIVATE_USES_FACE_DETECTION _T("Activate Uses Face Detection")
#define LIGHT_NORMALIZATION _T("Light normalization")
#define ENABLE_AUTOMATIC_RECALIBRATION _T("Enable Automatic Recalibration")
#define ADVANCED_SETTINGS_BUTTON _T("Advanced Settings")
#define USER_SETUP_WIZARD_BUTTON _T("User Setup Wizard")
#define SAVE_BUTTON _T("Save")
#define EXIT_BUTTON _T("Exit")
#define FILE_MENU _T("File")
#define LOAD_USERS_FILE_MENU_ITEM _T("Load user's file")
#define LOAD_DEFAULT_VALUES_INTO_MENU_ITEM _T("Load default values into")
#define SAVE_AS_MENU_ITEM _T("Save as")
#define SAVE_MENU_ITEM _T("Save ")
#define EXIT_MENU_ITEM _T("Exit")
#define LOAD_FILE_LOCATION_ERROR _T("Unable to read from this file location")
#define LOAD_IMPROPER_FORMAT_ERROR _T("Unable to read Improper format")
#define SAVE_FILE_ERROR _T("Unable to save to this file location")
#define SAVE_TO_DEFAULT_ERROR_PREFIX _T("Unable to save to")
#define SAVE_TO_DEFAULT_ERROR_SUFFIX _T("in this directory")
#define LOAD_DEFAULTS_ERROR_PREFIX _T("Unable to save to")
#define SAVE_TO _T("Save to")
#define ADVANCED_SETTINGS_TITLE _T("Advanced Settings")
#define SAVE_BOARD_ERROR _T("Unable to save to this file location")
#define USE_VOICE_COMMANDS _T("Use voice commands")
#define USE_MOUTH_CLICK _T("Use mouth click")
#define USE_MOUTH_CLICK_TOOL_TIP _T("Click by opening mouth")
#define MINIMUM_MOUTH_CLICK_HEIGHT _T("Minimum Mouth Click Height")
#define CLICK_ON_COMMAND _T("Click on command")
#define CLICK_ON_COMMAND_TOOL_TIP _T("In nouse cursor, if you open mouth or say \"click\" 0 means skip countdown. 1 means perform a left click")
//#define ALL_DIRECTIONS _T("All Directions")
//#define EIGHT_DIRECTIONS _T("8 Directions")
#define FOUR_DIRECTIONS _T("4 Directions")
#define DISCRETE_DIRECTION _T("Discrete Direction")
#define ENABLE_DWELL_CLICKING _T("Enable Dwell Clicking")
#define LAG_AVERAGE_POSITION_OVER_TIME _T("Lag (Average position over time)")
#define ALWAYS_LEFT_CLICK _T("Always Left Click")
#define ACTIVATE_ASSUMES_HEADWIDTH _T("Activate Assumes Headwidth")
#define ACTIVATE_ASSUMES_HEADWIDTH_TOOL_TIP _T("If face detection is not used, Nouse zooms in on the centre assuming a headwidth of 25% of image width")
#define NO_CHANGE_BACK_TO_RESET _T("\"No change back to reset\" (Seconds)")
#define NO_CHANGE_BACK_TO_RESET_TOOL_TIP _T("Automatically go to nose reset if Nouse cursor position doesn't change in this many seconds")
#define NO_MOTION_BACK_TO_RESET _T("\"No motion back to reset\" (Seconds)")
#define NO_MOTION_BACK_TO_RESET_TOOL_TIP _T("Automatically go to nose reset if No user motion is seen in this many seconds")
#define CLICK_CALIBRATION_BOX_SIZE _T("Click/Calibration box size")
#define JOYSTICK_NEUTRAL_ZONE _T("Joystick neutral zone")
#define JOYSTICK_NEUTRAL_ZONE_TOOL_TIP _T("Percentage of screen that is used for the \"stop box\" in joystick mode.")
#define CLOSE_CLICK_AMOUNT _T("\"Close\" Click Amount")
#define CLOSE_CLICK_AMOUNT_TOOL_TIP _T("How close you have to click to the previous click to be considered a \"close\" click.")
#define COUNTDOWN_CONFIRM_CLICK _T("Countdown Confirm Click")
#define COUNTDOWN_CONFIRM_CALIBRATION _T("Countdown Confirm Calibration")
#define CURSOR_LOCATION_RELATIVE_TO_NOUSE_CURSOR _T("Cursor location relative to Nouse Cursor")
#define CURSOR_LOCATION_RELATIVE_TO_NOUSE_CURSOR_TOOL_TIP _T("Top left = 0, Moves = 1, Always Center =2")
#define TOP_LEFT _T("Top left")
//#define MOVES _T("Moves")
#define CENTER _T("Center")
#define LOCK_ON_TOOL_TIP _T("0=all, 1=lower half, 2=upper half")
#define LOCK_ON _T("Lock-on")
//#define FOUR_DIRECTIONS_CROSS _T("4 Directions CROSS")
//#define FOUR_DIRECTIONS_X _T("4 Directions X")
#define DECREASING_JUMPS_COMPARISON_TYPE _T("Decreasing Jumps Comparison Type")
#define CALIBRATE_AUTOMATICALLY _T("Calibrate Automatically")
#define CALIBRATE_AUTOMATICALLY_TOOL_TIP _T("Unchecked Countdown while user puts nose in center, Checked Just guess where nose is after face detection")
#define BIG_MOTION_INDUCES_CALIBRATION _T("Big Motion Induces Calibration")
#define DISCRETE_NAVIGATION_TYPE _T("Discrete Navigation Type")
//#define DECREASING_JUMPS _T("Decreasing Jumps")
#define DIRECT_MAPPING _T("Direct Mapping")
#define DIRECT_MAPPING_ROWS _T("Direct Mapping Rows")
#define DIRECT_MAPPING_COLUMNS _T("Direct Mapping Columns")
#define BIG_MOTION_SIZE _T("Big Motion Size")
#define BIG_MOTION_SIZE_TOOL_TIP _T("Motion to be condsidered big how many pixels have to change (in % of image size)")
#define CONTROL_SETTINGS_TAB _T("Control Settings")
#define MIRROR_CAMERA_IMAGE _T("Mirror Camera Image")
#define CURSOR_SHOWS_FACE _T("Cursor Shows face")
#define TRANSLUCENT_CURSOR _T("Translucent Cursor")
#define TRANSLUCENCE_SOLIDNESS _T("Translucence \"Solidness\"")
#define TRANSLUCENT_CURSOR_TOOL_TIP _T("The Nouse Cursor will be translucent when in Nouse Cursor or Nouse Board mode.")
#define TRANSLUCENCE_SOLIDNESS_TOOL_TIP _T("If \"Translucent Cursor\" is checked, this determines how solid the translucency is. 0=transparent, 255=completely solid.")
#define CURSOR_SHOWS_COUNTDOWN _T("Cursor Shows Countdown")
#define WEBCAM_INDEX _T("Webcam Index")
#define PROCESS_LOAD_FILTER_NOISE _T("Process Load (Filter Noise)")
#define FACE_DETECTION_TYPE _T("Face Detection Type")
#define SHOW_DISCRETE_NAVIGATION_RECTANGLES _T("Show Discrete Navigation Rectangles")
#define VISUAL_SETTINGS_TAB _T("Visual Settings")
#define BOARD_TEXT_SCALE _T("Board Text Scale")
#define TEXT_SIZE_SCALE _T("Text Size Scale")
#define JITTER_THRESHOLD _T("Jitter Threshold")
#define NOUSE_CURSOR_IN_BOARD _T("Nouse Cursor in Board")
#define CURRENT_LEVEL _T("Current Level")
#define LOAD_BOARD_BUTTON _T("Load Board")
#define SAVE_BOARD_BUTTON _T("Save Board")
#define BOARD_SETTINGS_TAB _T("Board Settings")
#define SAVE_BUTTON_ADVANCED _T("Save")
#define CLOSE_BUTTON_ADVANCED _T("Close")
#define LOAD_BOARD_ERROR_LOCATION _T("Unable to read from this file location")
#define LOAD_BOARD_ERROR_FORMAT _T("Unable to read Improper format")